name: workout_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  flutter_tts: ^4.2.2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/exercise/
    - assets/gif/
    - assets/background/